// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu1nGO-OPzyrZDYFiipDDGMtR5neWqovo',
    appId: '1:868638675119:web:62239e664e51486bf4045a',
    messagingSenderId: '868638675119',
    projectId: 'news-23bab',
    authDomain: 'news-23bab.firebaseapp.com',
    storageBucket: 'news-23bab.appspot.com',
    measurementId: 'G-0RL6F05HKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSbk4_4fowKhVBM3igedKvMRE4QljQYaM',
    appId: '1:868638675119:android:ca5b1e3e8c37cfd4f4045a',
    messagingSenderId: '868638675119',
    projectId: 'news-23bab',
    storageBucket: 'news-23bab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy0GytREqkSAmYo49-CvunHAXHktruhQ0',
    appId: '1:868638675119:ios:0db4bc9023d6acb6f4045a',
    messagingSenderId: '868638675119',
    projectId: 'news-23bab',
    storageBucket: 'news-23bab.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy0GytREqkSAmYo49-CvunHAXHktruhQ0',
    appId: '1:868638675119:ios:0db4bc9023d6acb6f4045a',
    messagingSenderId: '868638675119',
    projectId: 'news-23bab',
    storageBucket: 'news-23bab.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu1nGO-OPzyrZDYFiipDDGMtR5neWqovo',
    appId: '1:868638675119:web:26e81b8d9aa3f76bf4045a',
    messagingSenderId: '868638675119',
    projectId: 'news-23bab',
    authDomain: 'news-23bab.firebaseapp.com',
    storageBucket: 'news-23bab.appspot.com',
    measurementId: 'G-L148BQK6XQ',
  );
}
